### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by tolga9009** [chrivers/samsung-firmware-magic#1]
Hi,

I wanted to try this out under Linux & Python 3.8.5, but I'm facing the following issue:

```
[tolga@estheim Samsung]$ ./samsung-magic.py < DSRD.enc 
Traceback (most recent call last):
  File "./samsung-magic.py", line 48, in <module>
    iv0 = "8ce82eefbea0da3c44699ed7".decode("hex")
AttributeError: 'str' object has no attribute 'decode'
```

As always with Python stuff, I suspect it's an issue with the Python version. What's the recommended version or the version you use?

Thanks!

**Comment by chrivers** [comment]
Ah, yes. That looks like a version problem.

I've updated the script to explicitly look for "python2" - can you pull and try again?

Please let me know if that solves the issue for you.

**Comment by tolga9009** [comment]
Thank you, I got it running now!
